const express = require('express');
const router = express.Router();
const { register, login, getProfile, uploadProfileImage, verifyToken, adminGetAllUsers, adminGetUserDetails, adminDeleteUser } = require('../controllers/authController');
const { authenticateToken } = require('../middleware/authMiddleware');
const { requireAdmin } = require('../middleware/adminMiddleware');
const { validateRegistration, validateLogin } = require('../middleware/validationMiddleware');
router.post('/register', validateRegistration, register);
router.post('/login', validateLogin, login);
router.get('/profile', authenticateToken, getProfile);
router.post('/profile/image', authenticateToken, uploadProfileImage);
router.get('/verify', authenticateToken, verifyToken);
router.get('/admin/users', authenticateToken, requireAdmin, adminGetAllUsers);
router.get('/admin/users/:id', authenticateToken, requireAdmin, adminGetUserDetails);
router.delete('/admin/users/:id', authenticateToken, requireAdmin, adminDeleteUser);
module.exports = router;
